version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jirai_u
      POSTGRES_PASSWORD: jirai_p
      POSTGRES_DB: jirai_d
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jirai_u"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
