version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jirai_u
      POSTGRES_PASSWORD: jirai_p
      POSTGRES_DB: jirai_d
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jirai_u", "-d", "jirai_d"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
